### ISSUE TITLE
path issue, can't use -p

### ISSUE THREAD

**Issue by MegaArman** [dromer/hvcc#176]
was this integrated here? https://github.com/enzienaudio/hvcc/issues/6 

I also have a module (.pd_linux) at the same level that isn't being seen. Working off debian linux

Any help would be much appreciated

**Comment by dromer** [comment]
I have not seen that commit before, but I also don't have any issue with adding search paths.
Can you give an example CLI command that you are trying to use?

A `.pd_linux` file is a compiled external, these you cannot use with Heavy. Only abstractions with compatible vanilla objects can be added to the path.
